### ISSUE TITLE
Allow students to push to repository

### ISSUE THREAD

**Issue by souza-diogo** [totvslabs/carol-ds-academy#14]
Good afternoon,

I've tried to push to a branch I had created locally to this repository, but got a 403 error (forbidden), so I assume we're not allowed to yet. Could you give us this permission, please?

Thanks!

**Comment by rafarui** [comment]
you need to `fork` instead of clone in this case. Since you are not in our organization, you will not be able of creating a branch direct here. 
With a fork you will be able to create a PR.

Here an explanation and they have instruction how to do.
https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/

Using gitHub it is easier. Just click on the Fork bottom on the top right, you will see that it will create a copy in you acc. From there (your account), when you try to open a PR you will see the option to open here.
